accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login_user, name='login'),
    url(r'^logout/', views.logout_user, name='logout'),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
]

redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name='home'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField
    published_date = models.DateTimeField
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default=1)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def signup(request):
    if request.method == 'POST':
        user = {
            'username': request.POST['username'],
            'password': request.POST['password'],
            'password_verification': request.POST['password_verification'],
            'email': "user@example.com",
        }
        if user['password'] == user['password_verification']:
            try:
                User.objects.get(username=user['username'])
                return render(request, 'accounts/signup.html', {'error': 'User already exists.'})
            except User.DoesNotExist:
                user = User.objects.create_user(user['username'], user['email'], user['password'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error': "Passwords do not match."})

    else:
        return render(request, 'accounts/signup.html')


def login_user(request):
    if request.method == 'POST':
        user = {
            'username': request.POST['username'],
            'password': request.POST['password'],
        }

        authenticated_user = authenticate(username=user['username'], password=user['password'])

        if authenticated_user is not None:
            login(request, authenticated_user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'Invalid login.'})

    else:
        return render(request, 'accounts/login.html')


def logout_user(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post


@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            post.url = request.POST['url']
            if post.url.startswith('http://') or post.url.startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.published_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('posts/home.html')
        else:
            return render(request, 'posts/create.html', {'error': 'Title or URL is missing. '})
    else:
        return render(request, 'posts/create.html')


def home(request):
    posts = Post.objects.order_by('votes_total')
    return render(request, 'posts/home.html', {'posts': posts})


def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')


def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Log-in Page</h1>

    {% if error %}
        <p>{{ error }}</p>
    {% endif %}

    <form method="POST" action="{% url 'accounts:login' %}">
        {% csrf_token %}

        {% if request.GET.next %}
            <input type="hidden" name="next" value={{ request.GET.next }}/>
        {% endif %}

        <label for="username">
            <span>Username:</span>
            <br>
            <input type="text" name="username"/>
        </label>
        <br>
        <label for="password">
            <span>Password:</span>
            <br>
            <input type="password" name="password"/>
        </label>
        <br>
        <br>
        <input type="submit" name="submit" value="Log-in">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Sign-Up Page</h1>

    {% if error %}
        <p>{{ error }}</p>
    {% endif %}

    <form method="POST" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        <label for="username">
            <span>Username:</span>
            <br>
            <input type="text" name="username"/>
        </label>
        <br>
        <label for="password">
            <span>Password:</span>
            <br>
            <input type="password" name="password"/>
        </label>
        <br>
        <label for="password_verification">
            <span>Confirm Password:</span>
            <br>
            <input type="password" name="password_verification"/>
        </label>
        <br>
        <input type="submit" name="submit" value="Sign Up">
    </form>
{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Post</h1>

    {% if error %}
        <p>{{ error }}</p>
    {% endif %}

    <form method="POST" action="{% url 'posts:create' %}">
        {% csrf_token %}

        {% if request.GET.next %}
            <input type="hidden" name="next" value={{ request.GET.next }}/>
        {% endif %}

        <label for="title">
            <span>Title:</span>
            <br>
            <input type="text" name="title"/>
        </label>
        <br>
        <label for="url">
            <span>URL:</span>
            <br>
            <input type="text" name="url"/>
        </label>
        <br>
        <br>
        <input type="submit" name="submit" value="Post">
    </form>
{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'posts:create' %}">New Post</a>
    <br>
    <br>
    {% for post in posts.all %}
        <div style="display: inline">
            <form method="POST" action="{% url 'posts:upvote' post.id %}" style="display: inline">
                {% csrf_token %}
                <input type="submit" value="UP">
            </form>
            <span>{{ post.votes_total }}</span>
            <form method="POST" action="{% url 'posts:downvote' post.id %}" style="display: inline">
                {% csrf_token %}
                <input type="submit" value="DOWN">
            </form>
        </div>
        <span>- <a href="{{ post.url }}">{{ post.title }}</a></span>
        <br>
        {{ post.published_date }} by {{ post.author.username }}
        <br>
        <br>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reddit Clone</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        img {
            width: 25%;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#" onclick="document.getElementById('logout').submit()">Logout</a></li>
                    <form id='logout' method="POST" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                {% else %}
                    <li><a href="{% url 'accounts:signup' %}">Sign-Up</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>